### PR TITLE
Update strings_aicp.xml

### PR DESCRIPTION
**Pull request by lasuria**
Translated what did not. (с) Robert Lasuriia

### CODE REVIEW

**Comment by LorDClockaN** [comment]
We have already a guy translating

also we don't accept github pushes, all goes over gerrit

thanks

**Comment by lasuria** [comment]
This guy does not translate many of the functions has long been, and many do not properly translated. I do not think it's bad that I do not much corrected translation and translated that did not translate for a week.

**Comment by LorDClockaN** [comment]
I've just merged his translations, so re check

**Comment by lasuria** [comment]
Can I continue to translate what was left and change what is not translated correctly? Of showing that I was translating I do not care, I'm more important than adequate translation. In the future, as translated begin to translate into Ukrainian language, but how should named values-ua, values-ua-nokeys, or values-ua-rUA ?

**Pull request closed without merging**
